# ============================================================================
# Core abstract types
# ============================================================================

# ----------------------------------------------------------------------------
# Execution environments
# ----------------------------------------------------------------------------
"""
    AbstractBendersEnv 

Abstract supertype for Benders execution environments.

An execution environment defines the algorithmic strategy used to coordinate the master problem and its oracles. 

See also: [`AbstractBendersSeq`](@ref), [`AbstractBendersBnB`](@ref)
"""
abstract type AbstractBendersEnv end

"""
    AbstractBendersSeq <: AbstractBendersEnv 

Abstract supertype for sequential Benders environments. 
    
Sequential environments repeatedly solve the master problem, query an oracle at the current candidate point, add cuts, and continue until a termination rule is met.
    
See also: [`BendersSeq`](@ref), [`BendersSeqInOut`](@ref)
"""
abstract type AbstractBendersSeq <: AbstractBendersEnv end

"""
    AbstractBendersBnB <: AbstractBendersEnv

Abstract supertype for branch-and-bound Benders environments. 
    
Branch-and-bound environments integrate Benders cut generation into the MIP solver's branch-and-bound process through solver callbacks.
    
See also: [`BendersBnB`](@ref)
"""
abstract type AbstractBendersBnB <: AbstractBendersEnv end

# ----------------------------------------------------------------------------
# Master problems
# ----------------------------------------------------------------------------

"""
    AbstractMaster

Abstract supertype for Benders master problems.

A master owns the optimization model seen by the environment, accepts cuts generated by oracles, and provides candidate solutions for oracle evaluation.

See also: [`Master`](@ref)
"""
abstract type AbstractMaster end

# ----------------------------------------------------------------------------
# Oracles
# ----------------------------------------------------------------------------

"""
    AbstractOracle

Abstract supertype for cut-generating oracles.

An oracle evaluates candidate master solutions and generates valid inequalities through [`generate_cuts`](@ref).

Concrete oracle implementations in BendersX conventionally store their adjustable parameters in a `param` field whose value is a subtype of [`AbstractOracleParam`](@ref).

See also: [`AbstractTypicalOracle`](@ref), [`AbstractDisjunctiveOracle`](@ref)
"""
abstract type AbstractOracle end

"""
    AbstractTypicalOracle <: AbstractOracle

Abstract supertype for typical Benders oracles.

See also: [`ClassicalOracle`](@ref)
"""
abstract type AbstractTypicalOracle <: AbstractOracle end

"""
    AbstractDisjunctiveOracle <: AbstractOracle

Abstract supertype for disjunctive Benders oracles.

Disjunctive oracles generate valid inequalities from disjunctive formulations associated with a candidate master solution.

See also: [`SplitOracle`](@ref)
"""
abstract type AbstractDisjunctiveOracle <: AbstractOracle end

# ----------------------------------------------------------------------------
# Oracle parameters
# ----------------------------------------------------------------------------

"""
    AbstractOracleParam

Abstract supertype for oracle parameter containers.

Oracle parameters collect tolerances and other adjustable settings controlling oracle behavior.

See also: [`BasicOracleParam`](@ref), [`AbstractOracle`](@ref)
"""
abstract type AbstractOracleParam end

# ============================================================================
# GBC (Generalized Bound Constraints) Bound Type
# ============================================================================

"""
    GBCBoundType

Sense of a generalized bound constraint (GBC).

The available values are:

- `UpperBound`: `lhs <= rhs`.
- `LowerBound`: `lhs >= rhs`.
- `Fixed`: `lhs == rhs`.
"""
@enum GBCBoundType begin
    UpperBound   # y ≤ f(x)
    LowerBound   # y ≥ f(x)
    Fixed   # y = f(x)
end

# ============================================================================
# Termination Status of Benders Decomposition
# ============================================================================
"""
    TerminationStatus

Abstract supertype for termination statuses of Benders execution environments.

These statuses describe the outcome of the overall Benders algorithm and are distinct from the solver-level statuses returned by `JuMP.termination_status(model)`.

Available statuses include:

- [`NotSolved`](@ref): The algorithm has not yet been executed.
- [`Optimal`](@ref): The algorithm terminated successfully.
- [`TimeLimit`](@ref): The algorithm terminated because the time limit was reached.
- [`InfeasibleOrNumericalIssue`](@ref): The algorithm terminated because of infeasibility or a numerical issue.
"""
abstract type TerminationStatus end

"""The Benders algorithm has not yet been executed."""
struct NotSolved <: TerminationStatus end

"""The Benders algorithm terminated because the time limit was reached."""
struct TimeLimit <: TerminationStatus end

"""The Benders algorithm terminated successfully."""
struct Optimal <: TerminationStatus end

"""The Benders algorithm terminated because of infeasibility or a numerical issue."""
struct InfeasibleOrNumericalIssue <: TerminationStatus end

# ============================================================================
# Error Exceptions
# ============================================================================

"""
    TimeLimitException <: Exception

Exception indicating that the time budget for the current Benders operation has been exhausted.

This exception may be raised by an execution environment or by an operation invoked during the solve, such as preprocessing, master optimization, oracle evaluation, or DCGLP separation.

The handling of this exception depends on where the time limit is reached. If the overall time budget of the execution environment is exhausted, the environment records [`TimeLimit`](@ref) as the algorithm-level termination status. If the exception arises within a recoverable subprocedure, such as preprocessing or DCGLP separation, the enclosing algorithm may terminate that subprocedure and continue using the information generated so far.
"""
struct TimeLimitException <: Exception
    msg::String
end

"""
    UnexpectedModelStatusException <: Exception

Exception indicating that a JuMP model returned a termination or solution status that is unexpected or unsupported by the current Benders operation.

The handling depends on where it occurs. Execution environments convert it to an algorithm-level termination status [`InfeasibleOrNumericalIssue`](@ref), while recoverable subprocedures may intercept it and continue using the information already generated.

See also: [`InfeasibleOrNumericalIssue`](@ref)
"""
struct UnexpectedModelStatusException <: Exception
    msg::String
end

"""
    UnimplementedInterfaceException <: Exception

Exception indicating that a required BendersX extension point has not been implemented for a concrete user-defined type.

This exception is raised when a concrete subtype does not provide a required method or constructor defined by the BendersX interface.

Examples include missing model-building functions, oracle methods, normalization methods, callback methods, or execution-environment methods.
"""
struct UnimplementedInterfaceException <: Exception
    msg::String
end

"""
    AlgorithmException <: Exception

Exception indicating that an algorithm-specific requirement or invariant has been violated, so the current Benders procedure cannot safely continue.

This exception is used for invalid algorithmic combinations, violated algorithm assumptions, or inconsistent algorithm state.

It is distinct from `ArgumentError`, which is used for invalid function arguments, and from [`UnsupportedModelException`](@ref), which is used when the model itself is outside the supported formulation class.
"""
struct AlgorithmException <: Exception 
    msg::String
end

"""
    UnsupportedModelException <: Exception

Exception indicating that a model or model feature is outside the class of formulations supported by the current BendersX component.

This exception should be used when the limitation is intrinsic to the algorithm or implementation rather than caused by an invalid algorithm configuration.

See also: [`AlgorithmException`](@ref)
"""
struct UnsupportedModelException <: Exception 
    msg::String
end

# ============================================================================
# Disjunctive cut-generation rules
# ============================================================================

# ----------------------------------------------------------------------------
# Split-index selection
# ----------------------------------------------------------------------------

"""
    SplitIndexSelectionRule

Abstract supertype for rules used to select the master variable defining a split disjunction.

Available rules include:

- [`RandomFractional`](@ref): Select a fractional master variable at random.
- [`MostFractional`](@ref): Select the fractional master variable whose value is closest to `0.5`.
- [`LargestFractional`](@ref): Select the fractional master variable with the largest index.
"""
abstract type SplitIndexSelectionRule end

"""
    SimpleSplit <: SplitIndexSelectionRule

Abstract supertype for split-selection rules based a single master variable.
"""
abstract type SimpleSplit <: SplitIndexSelectionRule end

"""Select a fractional split index at random."""
struct RandomFractional <: SimpleSplit end

"""Select the split index with value closest to 0.5."""
struct MostFractional <: SimpleSplit end

"""Select the largest-index fractional master variable."""
struct LargestFractional <: SimpleSplit end

# ----------------------------------------------------------------------------
# Disjunctive-cut inclusion
# ----------------------------------------------------------------------------

"""
    DisjunctiveCutsAppendRule

Abstract supertype for rules controlling which previously generated disjunctive cuts are included in the DCGLP.

Available rules include:

- [`NoDisjunctiveCuts`](@ref): Do not include previously generated disjunctive cuts.
- [`AllDisjunctiveCuts`](@ref): Include all previously generated disjunctive cuts.
- [`DisjunctiveCutsSmallerIndices`](@ref): Include only disjunctive cuts associated with smaller split indices.
"""
abstract type DisjunctiveCutsAppendRule end

"""Do not include previously generated disjunctive cuts in the DCGLP."""
struct NoDisjunctiveCuts <: DisjunctiveCutsAppendRule end

"""Include all previously generated disjunctive cuts in the DCGLP."""
struct AllDisjunctiveCuts <: DisjunctiveCutsAppendRule end

"""Include only disjunctive cuts associated with smaller split indices in the DCGLP."""
struct DisjunctiveCutsSmallerIndices <: DisjunctiveCutsAppendRule end
